### ISSUE TITLE
`Error loading shared library ld-linux-x86-64.so.2` on running jar over http

### ISSUE THREAD

**Issue by Tatskaari** [docker-flink/docker-flink#69]
Hi guys, I'm using the image tagged `1.7.2-scala_2.11-alpine` however I seem to be getting shared lib issues. I'm submitting my pipelines via the http API and it's throwing the following exception when constructing the job graph:
```java
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.4-a1c7fa1d-2146-4884-8450-3c5b7ad994a3-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.4-a1c7fa1d-2146-4884-8450-3c5b7ad994a3-libsnappyjava.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:97)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:89)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:79)
	at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:50)
	at org.apache.beam.sdk.util.SerializableUtils.clone(SerializableUtils.java:100)
	at org.apache.beam.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:79)
	at org.apache.beam.sdk.io.Read$Unbounded.<init>(Read.java:129)
	at org.apache.beam.sdk.io.Read$Unbounded.<init>(Read.java:124)
	at org.apache.beam.sdk.io.Read.from(Read.java:56)
	at org.apache.beam.sdk.io.kafka.KafkaIO$Read.expand(KafkaIO.java:725)
	at org.apache.beam.sdk.io.kafka.KafkaIO$Read.expand(KafkaIO.java:309)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:471)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:44)
	at org.apache.beam.sdk.io.kafka.KafkaIO$TypedWithoutMetadata.expand(KafkaIO.java:837)
	at org.apache.beam.sdk.io.kafka.KafkaIO$TypedWithoutMetadata.expand(KafkaIO.java:826)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:471)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:44)
	at net.thoughtmachine.common.streamio.KafkaRead.expand(KafkaRead.java:31)
	at net.thoughtmachine.common.streamio.KafkaRead.expand(KafkaRead.java:11)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:488)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:56)
	at net.thoughtmachine.balance.BalancePipeline.lambda$expand$0(BalancePipeline.java:29)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.thoughtmachine.balance.BalancePipeline.expand(BalancePipeline.java:30)
	at net.thoughtmachine.balance.BalancePipeline.expand(BalancePipeline.java:17)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:488)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:56)
	at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:182)
	at net.thoughtmachine.balance.FlinkBalancePipeline.main(FlinkBalancePipeline.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:78)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:120)
	at org.apache.flink.runtime.webmonitor.handlers.utils.JarHandlerUtils$JarHandlerContext.toJobGraph(JarHandlerUtils.java:117)
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$getJobGraphAsync$7(JarRunHandler.java:151)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Seems that snappy can't find `ld-linux-x86-64.so.2`. Looking at the image, this should have been installed. 

I tried the debian based image quickly and that works fine however it's not really suitable for our purposes as we'd like to keep to alpine across the board if possible.

**Comment by Tatskaari** [comment]
Ah, so JVM isn't looking in that folder for it. I added `ENV LD_LIBRARY_PATH=/lib64` to my docker image and it works now.

**Comment by xanonid** [comment]
At least, current `1.7.2-scala_2.11-alpine` is also affected. Its build before Februar 7 2019 worked. 

The root cause is that the used base image `openjdk:8-jre-alpine` updated to from alpine 3.8 to alpine 3.9. In alpine 3.8 `/lib64` is a symlink to `/lib`, in alpine `/lib64` is a separate folder and `ld-linux-x86-64.so.2` cannot be longer found in `/lib`. As `/lib64` is not in the default search path, libc6-compat is broken which caused the here discussed snappy bug.

Until the upstream bug reported now as https://bugs.alpinelinux.org/issues/10140 is solved, it would be nice if the ENV var suggested by @Tatskaari is included in the official flink alpine docker image or a /lib/ld-`linux-x86-64.so.2`  -> `/lib/libc.musl-x86_64.so.1` symlink is created.

**Comment by patricklucas** [comment]
This seems like a reasonable improvement.

I would consider a PR for this, provided it includes some way of testing whether the setting is still valid—if upstream fixes the bug, I wouldn't want these images to again break.
