### ISSUE TITLE
Kubernetes: Task manager failed to flink-jobmanager name resolution .

### ISSUE THREAD

**Issue by yogeshbombepune** [docker-flink/docker-flink#98]
> java.net.UnknownHostException: flink-jobmanager: Temporary failure in name resolution
>         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
>         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
>         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
>         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
>         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
>         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
>         at java.net.InetAddress.getByName(InetAddress.java:1077)
>         at org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils.getRpcUrl(AkkaRpcServiceUtils.java:203)
>         at org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils.getRpcUrl(AkkaRpcServiceUtils.java:169)
>         at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:97)
>         at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.<init>(TaskManagerRunner.java:132)
>         at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManager(TaskManagerRunner.java:312)
>         at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.lambda$runTaskManagerSecurely$2(TaskManagerRunner.java:326)
>         at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
>         at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManagerSecurely(TaskManagerRunner.java:325)
>         at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.main(TaskManagerRunner.java:291)

**Comment by iemejia** [comment]
We are not tracking new issues in this repo since the project moved now to https://github.com/apache/flink-docker If you want to fill a new issue please use the FLINK Apache JIRA issue tracker https://issues.apache.org/jira/projects/FLINK/issues/

**Comment by iemejia** [comment]
@patricklucas we should probably disable the issues section here or let it read only to avoid future possible confusion.

**Comment by patricklucas** [comment]
Good idea, I'll do that now.
